# Prometheus JMX Exporter 配置示例
startDelaySeconds: 0
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:9010/jmxrmi
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: 'java.lang<type=Memory><>(HeapMemoryUsage|NonHeapMemoryUsage)'
    name: jvm_memory_used_bytes
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=GarbageCollector,name=(.+)><>CollectionTime'
    name: jvm_gc_pause_seconds
    type: COUNTER
    attrNameSnakeCase: true
